security:
    encoders:
        App\Entity\Profil:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        classeProfil:
            entity:
                class: App\Entity\Profil
                property: email
    firewalls:
        main:
            pattern:   ^/
            http_basic: ~
            provider: classeProfil
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            form_login:
                login_path: login
                check_path: security_login
            logout:
                path:  /logout
                target: /

    access_control:
        - { path : ^/gestionPraticien, roles : [ ROLE_VISITEUR , ROLE_RESPONSABLE] }
        - { path: ^/home ,roles : ROLE_USER }
        - { path: ^/visiteur, roles: ROLE_VISITEUR }
        - { path: ^/responsable, roles: ROLE_RESPONSABLE }
        - { path: ^/comptable, roles: ROLE_COMPTABLE }
