security:
    encoders:
        App\Entity\Profil:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        classeProfil:
            entity:
                class: App\Entity\Profil
                property: email
    firewalls:
        main:
            pattern:   ^/
            http_basic: ~
            provider: classeProfil
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:  /logout
                target: /login

    access_control:
        - { path: ^/visiteur, roles: ROLE_VISITEUR }
        - { path: ^/responsable, roles: ROLE_RESPONSABLE }
        - { path: ^/comptable, roles: ROLE_COMPTABLE }
